version: "3.7"

services:
  apilytics-db:
    container_name: apilytics-db
    image: postgres:14.2-alpine3.15@sha256:da0b571d3abdfbd20aee7d696d817c5ff0565e7bf4cb65343455974dea7e7792
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=apilytics
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
    volumes:
      - apilytics_postgres_data:/var/lib/postgresql/data/
    restart: unless-stopped

  apilytics:
    container_name: apilytics
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    env_file: .env
    depends_on:
      - apilytics-db
    restart: unless-stopped

volumes:
  apilytics_postgres_data:
