version: "3.7"

services:
  apilytics-db:
    container_name: apilytics-db
    image: postgres:12.8-alpine3.14@sha256:e88c1e9e117d09730cc9da8414f99ce36bda5d435eca273d6feca8919b2b445c
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=apilytics
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
    volumes:
      - apilytics_postgres_data:/var/lib/postgresql/data/
    restart: unless-stopped

  apilytics:
    container_name: apilytics
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    env_file: .env
    depends_on:
      - apilytics-db
    restart: unless-stopped

volumes:
  apilytics_postgres_data:
