version: "3.7"

services:
  apilytics-db:
    container_name: apilytics-db
    image: postgres:12.4-alpine@sha256:4c493832e4865189e3cab86281a1706a074ea6796b525a7f191b3f48546c25a8
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=apilytics
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
    volumes:
      - apilytics_postgres_data:/var/lib/postgresql/data/
    restart: unless-stopped

  apilytics-landing-page:
    container_name: apilytics-landing-page
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - .:/home/user/app
      - /home/user/app/node_modules
      - /home/user/app/.next
    depends_on:
      - apilytics-db
    restart: unless-stopped
    env_file: ./.env.local

volumes:
  apilytics_postgres_data:
